troubleshoot win arm

diff --git a/.github/workflows/build-python-wheels.yml b/.github/workflows/build-python-wheels.yml
--- a/.github/workflows/build-python-wheels.yml
+++ b/.github/workflows/build-python-wheels.yml
@@ -96,6 +96,13 @@ jobs:
         run: |
           # ring crate: add Visual Studio Build Tools "VS 2022 C++ ARM64 build tools" and "clang" components
           echo 'C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\x64\bin' >> "$GITHUB_PATH"
+          echo 'Output GITHUB_PATH'
+          cat "$GITHUB_PATH"
+          echo 'Output PowerShell PATH'
+          pwsh -c '$env:Path' || true
+          echo 'Checking if build tools exist'
+          ls -hal 'C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\x64\bin'
+          exit 1 # fail because we are testing
 
       - name: Build wheels
         uses: PyO3/maturin-action@b9e8f88fd4448fdecf5095864cdc7e39a544aa9f # v1.40.7
