windows use the dynamically linked .lib file for c++

diff --git a/.github/workflows/build-cpp.yml b/.github/workflows/build-cpp.yml
--- a/.github/workflows/build-cpp.yml
+++ b/.github/workflows/build-cpp.yml
@@ -116,7 +116,8 @@ jobs:
             ls include/libbitwarden_c.* || { echo "Missing libbitwarden_c.*"; exit 1; }
           fi
           if [[ '${{ runner.os }}' == 'Windows' ]]; then
-            ls include/bitwarden_c.lib || { echo "Missing bitwarden_c.lib"; exit 1; }
+            ls include/bitwarden_c.dll || { echo "Missing bitwarden_c.dll"; exit 1; }
+            ls include/bitwarden_c.dll.lib || { echo "Missing bitwarden_c.dll.lib"; exit 1; }
           fi
           rmdir include/release
 
@@ -165,7 +166,7 @@ jobs:
         run: |
           mkdir build
           cd build
-          $env:DTARGET="include\bitwarden_c.lib"
+          $env:DTARGET="include\bitwarden_c.dll.lib"
           cmake .. -DTARGET="%DTARGET%" -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake"
           cmake --build . --config Release
         shell: pwsh
